apiVersion: v1
kind: Namespace
metadata:
  name: svc-master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetapp-deployment
  namespace: svc-master
  labels:
    app: dotnetapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnetapp
  template:
    metadata:
      labels:
        app: dotnetapp
    spec:
      containers:
      - name: dotnetapp
        image: vtest1container.azurecr.io/sabbavarapu/azure-devops-kubernetes:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dotnetapp
  namespace: svc-master
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: dotnetapp
